### ISSUE TITLE
2 - AVR - a) Crear cuaderno PDF de la carpeta “Estructura del controlador AVR de 8 bits”

### ISSUE THREAD

**Issue by chulkx** [EMTSTISPC/Grupo7#3]

**Comment by ruizgb** [comment]
Se trabaja en forma conjunta para verificar la información.

**Comment by chulkx** [comment]
De hecho, ademas de tener razon en eso, no puedo abrir el documento, como si el mismo estuviera roto.

**Comment by chulkx** [comment]
Aunque si puedo descargarlo y verlo correctamente. Luego lo vuelvo a subir.
